###

POST http://localhost:8000/user/register
 Content-Type: application/json

 {
    "firstName": "Tes",
    "lastName": "Lay",
    "email": "acotes@weRETs.co.uk",
    "password": "kjehwroihtn,knfkdjknd"
 }